// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LOGISTICA_BE.Entities
{
    public partial class CategoriasProducto
    {
        public int Id { get; set; }
        public string categoriaProducto { get; set; }
    }
}