// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LOGISTICA_BE.Entities
{
    public partial class Usuario
    {
        public int Id { get; set; }
        public string email { get; set; }
        public int id_tipo_Usuario { get; set; }
        public DateTime fecha_creacion { get; set; }
        public int? borrado { get; set; }
        public DateTime? fecha_borrado{ get; set; }
    }
}