// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LOGISTICA_BE.Entities
{
    public partial class UsuarioPerfil
    {
        public int Id { get; set; }
        public string email { get; set; }
        public string? Tipo_Usuario { get; set; }
        public string? Familias_Asignadas { get; set; }
        public string? patentesIndividuales_Asignadas { get; set; }
        public string? patentesPorFamilia_Asignadas { get; set; }
    }
}